### ISSUE TITLE
`ElFel.jl` vs `FinEtools.jl`

### ISSUE THREAD

**Issue by bhaveshshrimali** [PetrKryslUCSD/Elfel.jl#3]
Hi @PetrKryslUCSD 

I had come across both `FinEtools` and `ElFel` and wanted to get an understanding of what are the potential use cases for each? 

For instance, `FinEtools` seems to be more mature and frequently mantained whereas `ElFel` seems simple and extendable. I am asking as a potential user who wants to implement and test new elements for applications in solid mechanics but at the same time for problems that are sufficiently large ( > 100k elements) and also, often, nonlinear. 

Is implementing a new `FESet` in `FinEtools` or a new `FE` in `ElFel` the only step in the finite element pipeline required to implement new elements? 

I understand that very large problems with millions on dofs may not be feasible without any sort of distributed memory parallelism. Currently I use either Abaqus-UEL or FEniCS for these.

Either of `ElFel` or `FinEtools` could be useful for me as a substitute for writing a UEL in Abaqus.

I also see multi-threading support in `FinEtools` which could prove useful in the FE assembly. I guess there is a lot to uncover but I would definitely like to know your views on the above queries.

**Comment by PetrKryslUCSD** [comment]
Hi,

I will come back to you on this next week. I will be off line this weekend.

P

**Comment by bhaveshshrimali** [comment]
Thanks. No hurries at my end.

**Comment by PetrKryslUCSD** [comment]
FinEtools or Elfel? It depends on the goals. I have developed both to support my research.
Right now I work on something for which FinEtools is more convenient, and hence it picked up some
recent improvements. Before then I was using Elfel for another research project.

FinEtools packages up the functionality into finite element model machines. 
Elfel design philosophy is different: instead of providing packaged functionality, the user
is free to implement his or her own discrete forms.

**Comment by bhaveshshrimali** [comment]
Thanks @PetrKryslUCSD I will take a look at Elfel more closely. I really like the simple (and extensible) design.:) 

I will start with some simple problems in hyperelasticity to get a feel for the package and then take it from there. Thanks!
